@BASEURL = http://localhost:3000

### Get All Prompts
GET {{BASEURL}}/pms

### Get a Prompt by ID
GET {{BASEURL}}/pms/1

### Create a New Prompt
POST {{BASEURL}}/pms
Content-Type: application/json

{
  "text": "This is a test prompt"
}

### Update a Prompt by ID
PUT {{BASEURL}}/pms/1
Content-Type: application/json

{
  "text": "This prompt has been updated"
}

### Delete a Prompt by ID
DELETE {{BASEURL}}/pms/1
